erDiagram
    direction LR

    USERS {
        Guid Id PK
        string Email
        string PasswordHash
        string Role
        string ame
        string 
        datetime CreatedAt
        datetime UpdatedAt
    }

    COMPANIES {
        Guid Id PK
        string Name
        string NIP
        datetime CreatedAt
        datetime UpdatedAt
        string Token
    }

    COMPANY_ADDRESS {
        Guid Id PK
        string Street
        string City
        string ZipCode
        double Latitude
        double Longitude
        datetime CreatedAt
        datetime UpdatedAt
        Guid CompanyId FK
    }

    CONTACTS {
        Guid Id PK
        string FirstName
        string LastName
        Guid ContactDetailsId FK
        string Token
        datetime CreatedAt
        datetime UpdatedAt
        Guid CompanyId FK
        Guid OwnerId FK
    }

    CONTACTS_DETAILS {
        Guid Id PK
        string Email
        string Phone
        datetime CreatedAt
        datetime UpdatedAt
    }

    DEALS {
        Guid Id PK
        string Name
        int Value %% wartość w groszach
        string Stage
        int Probability
        datetime CloseDate
        Guid CompanyId FK
        Guid OwnerId FK
        datetime CreatedAt
        datetime UpdatedAt
    }

    TASKS {
        Guid Id PK
        string Title
        string Description
        datetime DueAt
        Guid AssignedToId FK
        Guid ContactId FK
        Guid DealId FK
        string Token
        datetime CreatedAt
        datetime UpdatedAt
        %% TaskStatusEnum: ToDo, InProgress, Complete
        %% TaskPriorityEnum: Low, Medium, High
    }

    NOTES {
        Guid Id PK
        string Content
        datetime CreatedAt
        Guid AuthorId FK
        Guid ContactId FK
        Guid DealId FK
        datetime CreatedAt
        datetime UpdatedAt
    }

     PRODUCT_CATEGORIES {
        Guid Id PK
        string Name %% nazwa np. Blachy i płaskowniki
        string Description %% opis kategorii Wyroby stalowe płaskie
        datetime CreatedAt
        datetime UpdatedAt
    }

    PRODUCT_TYPES {
        Guid Id PK
        string Name %% nazwa np. Blachy gorącowalcowane
        string Description %% opis typu np. Blachy walcowane na gorąco o różnych grubościach i wymiarach
        Guid CategoryId FK
        datetime CreatedAt
        datetime UpdatedAt
    }

    PRODUCTS {
        Guid Id PK
        string Name %% nazwa np. Blacha gorącowalcowana
        string SteelGrade %% typ stali np. S235JR, S355J2H
        int Thickness %% grubość w mm
        int Width %% szerokość w mm
        int Length %% długość w mm
        int Diameter %% średnica w mm
        int Weight %% w kg
        string Unit %% jednostka miary np. kg, m, szt.
        int PricePerUnit %% cena za jednostkę miary w groszach
        Guid ProductTypeId FK
        datetime CreatedAt
        datetime UpdatedAt
    }

    DEAL_PRODUCTS {
        Guid Id PK
        Guid DealId FK
        Guid ProductId FK
        int Quantity %% ilość w najmniejszej jednostce (np. sztuk, kg, m)
        int UnitPrice %% cena za jednostkę miary w groszach
        datetime CreatedAt
        datetime UpdatedAt
    }


    %% RELACJE
    USERS ||--o{ CONTACTS : owns
    USERS ||--o{ DEALS : manages
    USERS ||--o{ TASKS : assigned
    USERS ||--o{ NOTES : writes

    COMPANIES ||--o{ CONTACTS : has
    COMPANIES ||--o{ DEALS : has
    COMPANIES ||--|| COMPANY_ADDRESS : has

    CONTACTS ||--|| CONTACTS_DETAILS : has
    CONTACTS ||--o{ TASKS : related
    CONTACTS ||--o{ NOTES : has

    DEALS ||--o{ TASKS : related
    DEALS ||--o{ NOTES : has

    PRODUCT_CATEGORIES ||--o{ PRODUCT_TYPES : contains
    PRODUCT_TYPES ||--o{ PRODUCTS : defines
    DEALS ||--o{ DEAL_PRODUCTS : includes
    PRODUCTS ||--o{ DEAL_PRODUCTS : sold_in